/control/verbose 0
/run/verbose 0
/tracking/verbose 0
/event/verbose 0
#/stepping/verbose 0
/run/printProgress 0


#/testhadr/phys/thermalScattering  false

#/B02/gun/rndm off
#/gun/energy 5 GeV

/generator/SmithActivation true 

/analysis/setFileName muons_file
/analysis/ntuple/setFileName 0 ../ROOTanalysis/root_files/muons_1M_vacuum_400x525_file
/analysis/ntuple/setFileName 1 ../ROOTanalysis/root_files/muons_1M_vacuum_400x525_file

/run/beamOn 1000000



