/control/verbose 0
/run/verbose 0
/tracking/verbose 0
/event/verbose 0
#/stepping/verbose 0
/run/printProgress 0


#/testhadr/phys/thermalScattering  false

#/B02/gun/rndm off
#/gun/energy 5 GeV

/generator/SmithActivation true 

/analysis/setFileName muons_file

/analysis/ntuple/setFileName 0 ../ROOTanalysis/root_files/muons_500K_SimCOMPLETE_1
/analysis/ntuple/setFileName 1 ../ROOTanalysis/root_files/muons_500K_SimCOMPLETE_1 

/run/beamOn 500000



